services:
  web:
    image: odoo:17.0
    container_name: proyecto_odoo_ADM_moduls_web
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    container_name: proyecto_odoo_ADM_moduls_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
    name: proyecto_odoo_ADM_moduls_web
  odoo-db-data:
    name: proyecto_odoo_ADM_moduls_db
